### ISSUE TITLE
Optimized web-page link to normalized absolute link

### ISSUE THREAD

**Issue by markov2** [sysread/URI-Fast#34] opened 2021-07-27 16:43 UTC
Not only my project, but also many other people, convert links which are found somewhere (usually in HTML, maybe in config files) into absolute, normalized urls.  My application has to do this at least 150k times per second, for ever.  Library support to speed this up is very welcome to save resources (the planet).

Current flow with XML::LibXML:
```perl
   foreach my a ($doc->findnodes("//a[@href]")) {
      my $href = $a->getAttribute('href') =~ s/^\s+//r =~ s/\s+$//r;
      my $uri = URI::Fast->new($href)->absolute($base)->canonical;
      ...
   }
```
The best performing would be
```perl
   URI::Fast->defaultBase($base);
   foreach my a ($doc->findnodes("//a[@href]")) {
       my $uri = URI::Fast->newFromHtml($a->getAttribute('href'));
       ...
   }
```

**Comment by sysread** [comment] 2021-07-27 17:36
This seems like a reasonable addition to https://github.com/sysread/URI-Fast/pull/26, which is adding better normalization for URIs coming from HTML. I'm trying to decide if this should be added as a default behavior or if it should be a separate method.

**Comment by sysread** [comment] 2021-08-06 17:28
Also, I assume that in the example, `->canonical` was intended to be `->normalize`.

**Comment by sysread** [comment] 2021-08-08 19:40
I am not certain I want to add global state to `URI::Fast`, as it could easily lead to weird bugs when two consumers of `URI::Fast` have different ideas of the "default base".

Currently, `html_url` provides the means to provide a "source URI". If specified, any URL beginning with `//` adopts the scheme from the source URI. Is this sufficient for your needs?

**Comment by markov2** [comment] 2021-08-08 20:16
The actual process I currently perform for each discovered links to make it absolute is:
```perl
my $base = ...   # <base href>, default page location
my $link = ...  # for instance <a href> or <script src> or ...
s/^\s+//s,s/\s+\z//s for $link;
return $URI->new_abs($lin, $base)->canonical;
```
For the whole page (average 120 links), the base is the same.
Your '//' is part of the absolute making.  Terms 'canonical' and 'normalize' are both used for the same, AFAIK.
Thank you for your work!

**Comment by sysread** [comment] 2021-08-09 00:25
I updated the docs to note that canonical is an alias for normalize. 

Does the current functionality sufficiently address your use case?

**Comment by markov2** [comment] 2021-08-09 06:54
Yes.  This issue requests a peephole optimized version of this process, because I need to run it 150k per second.  The better this process works, the fewer servers I will need to run the application.

**Comment by sysread** [comment] 2021-08-14 20:22
I've got what I believe is a working setup for you as of `5fb4c17`. The function you want is `URI::Fast::abs_html_url($url, $base)`, which normalizes, makes absolute, and makes canonical. If this covers everything requested in this ticket, let me know, and I'll push it to CPAN.

**Comment by markov2** [comment] 2021-08-14 21:04
I am impressed!  (When you add `#34` to your commits, they will show up in this issue log)

Probably a small bug in the docs:
```perl
  my $url = html_url("//www.slashdot.org/recent/..", $base)
    ->absolute($base)
```
As I understand now, when you specify the optional `$base` to `html_url()` is does `absolute()` already.

I do not really understand why some features offered are functions, where other things are methods.  Afraid for multiple constructors?

**Comment by sysread** [comment] 2021-08-14 23:18
1. `html_url` does not return an absolute URI. If the input URL begins with `//`, it will adopt the scheme of the base URL. That's per the RFCs cited by Chas Owens, who made the original request of the feature.
2. As far as constructors, I _prefer_ exported subroutines. I made `new_abs` because you specifically asked for it :P

**Comment by sysread** [comment] 2021-08-14 23:18
Are the docs not clear enough about the behavior of `html_url`? Do you have any suggestions for how to improve them?

**Comment by markov2** [comment] 2021-08-16 07:15
1.  Isn't taking the scheme from a base uri not just a rule like other rules to make a relative uri into an absolute uri?  When my relative uri is `/path`, then the absolute version also copies the scheme from the base.  I see no reason for special treatment of the scheme.
2. Well, your object offers a large part of the functionality of URI and new_abs() is a very useful method on URIs.  There are more modules which offer both an functional as an OO interface for their functionality... it may be an advantage that the user can decide which fits better in their programming style.  However, when those interfaces do not offer the same functionality, it becomes a disadvantage for the user, IMHO.

**Comment by sysread** [comment] 2021-08-16 12:45
1. We worked the behavior from https://url.spec.whatwg.org/#concept-url-parser and https://www.w3.org/TR/html52/infrastructure.html#parsing-urls. I did not take those as meaning that all urls starting with `//` should be treated as relative and made absolute based from the parent document, but I'm open to the suggestion.
2. Fair enough. I'll work on making it more consistent, providing both OO constructors and equivalent sub exports.

**Comment by sysread** [comment] 2021-08-16 15:20
#2 is addressed in 8dab762. I updated the docs as well.

**Comment by sysread** [comment] 2021-08-16 15:22
It would certainly simplify the whole thing to just merge the two to always behave the same when a base url is passed. I think that is probably the right way to go.

**Comment by sysread** [comment] 2021-08-16 18:51
Ok, I went ahead and did that in b32cbae. Would you confirm that `html_url` and `new_html_url` behave as you need? And that their performance is acceptable?

**Comment by markov2** [comment] 2021-08-17 07:51
After this week of holidays, I will benchmark it.  But I read the code, and it looks sane.

**Comment by sysread** [comment] 2021-08-17 13:11
A quick benchmark gave ~1350% over `URI->new('some/path')->abs('http://www.example.com/fnord')->canonical`. If you are offline this week, I can go ahead and release this and we can refine it as needed in future releases. I'd like to get at least a dev release out so cpantesters can give it a smoke test.

**Comment by markov2** [comment] 2021-08-18 09:37
Please release, while I am sheltering from rain in my tent ;-)

**Comment by sysread** [comment] 2021-08-20 19:38
Dev release looked good. Just posted v0.52 with these changes to cpan. If the performance does not meet requirements, please submit a new ticket for that. Hope you enjoyed your tent and your rain! :)

**Closed as completed by sysread** 2021-08-20 19:38 UTC
Labels: enhancement
